spring.application.name=eksamen-band-backend

spring.datasource.url=${DATABASE_URL:jdbc:mysql://127.0.0.1:3306/band_db}
spring.datasource.username=${DATABASE_USERNAME:jens}
spring.datasource.password=${DATABASE_PASSWORD:x}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:io5SRxVOThlvptZLfNZSa97vU+33VTTmr7YRwhlgeUo=}

app.upload-dir= ${UPLOAD_DIR:uploads}